---
apiVersion: batch/v1
kind: Job
metadata:
  name: pgdump
spec:
  backoffLimit: 0
  template:
    metadata:
      name: pgdump
      labels:
        app: pgdump
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-db-creds: "cf-deployer/dev/AdmiralDatabasePasswordEric"
        vault.hashicorp.com/role: "kubernetes-controller"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-log-level: "debug"
    spec:
      serviceAccountName: vault-injector
      containers:
      - name: pgdump
        image: postgres:11.5
        command:
          - "/bin/sh"
          - "-ec"
        args:
          - "/usr/bin/pg_dump $(cat /vault/secrets/db-creds) --no-owner > /dev/stdout"
      restartPolicy: Never