AWSTemplateFormatVersion: 2010-09-09
Description: Pies Stack
Parameters:
  ClusterName:
    Description: The name of the ECS cluster
    Type: String
  ServiceName:
    Description: The name of the service.
    Type: String
    Default: pies
  DBName:
    Description: The name of the database
    Type: String
    Default: pies
  DBUser:
    Description: Root RDS Username
    Type: String
    Default: pies
  DBPassword:
    Description: Root RDS Password
    Type: String
    Default: ''
    NoEcho: true
Resources:
  RDS:
    Type: AWS::RDS::DBInstance  
    DeletionPolicy: Retain
    Properties:
      AllocatedStorage: db.r4.large
      AllowMajorVersionUpgrade: false
      BackupRetentionPeriod: 1
      DBInstanceClass: !Ref DBInstanceClass
      DBInstanceIdentifier: !Sub ${ServiceName}-${ClusterName}-${AWS::Region}
      DBName: !Ref DBName
      DBSubnetGroupName:
        Fn::ImportValue:
          !Sub harbour:${AWS::Region}:${ClusterName}:RDSSubnetGroup
      Engine: aurora
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      MultiAZ: true
      PubliclyAccessible: false
      StorageEncrypted: true
      StorageType: !Ref DBStorageType
      Tags:
        - Key: Name
          Value: !Sub pies ${ClusterName}
        - Key: Role
          Value: !Ref Role
        - Key: Service
          Value: !Ref Service
        - Key: Business-Unit
          Value: !Ref BusinessUnit
        - Key: Owner
          Value: !Ref Owner
      VPCSecurityGroups:
        - Fn::ImportValue:
            !Sub harbour:${AWS::Region}:${ClusterName}:RDSSecurityGroup
