AWSTemplateFormatVersion: 2010-09-09
Description: Pies Stack
Parameters:
  ClusterName:
    Description: The name of the ECS cluster
    Type: String
  ServiceName:
    Description: The name of the service.
    Type: String
    Default: pies
  DockerImage:
    Description: The docker image to run.
    Type: String
    Default: drydock.workiva.net/ericlarssen-wf/pies:make-pies-great-again-latest
  GithubClientId:
    Description: The Github OAuth application client id.
    Type: String
    Default: ''
  GithubClientSecret:
    Description: The Github OAuth application client secret.
    Type: String
    Default: ''
    NoEcho: true
  SecretKey:
    Description: The Secret Key.
    Type: String
Resources:
  ECSTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Cpu: 1024
          DockerLabels:
            harbour.dev-log.enable: 'true'
            harbour.service.name: !Ref ServiceName
            harbour.service.version: default
          Environment:
            - Name: GITHUB_CLIENT_ID
              Value: !Ref GithubClientId
            - Name: GITHUB_CLIENT_SECRET
              Value: !Ref GithubClientSecret
            - Name: SECRET_KEY
              Value: !Ref SecretKey
          Essential: true
          Image: !Ref DockerImage
          Memory: 512
          Name: !Ref ServiceName
          Entrypoint:
            - "pies"
      Volumes: []
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      DesiredCount: 1
      TaskDefinition: !Ref ECSTaskDef
