AWSTemplateFormatVersion: 2010-09-09
Description: Pies Stack
Parameters:
  ClusterName:
    Description: The name of the ECS cluster
    Type: String
  ServiceName:
    Description: The name of the service.
    Type: String
    Default: pies
  DBName:
    Description: The name of the database
    Type: String
    Default: pies
  DBUser:
    Description: Root RDS Username
    Type: String
    Default: pies
  DBPassword:
    Description: Root RDS Password
    Type: String
    Default: ''
    NoEcho: true
Resources:
  RDS:
    Type: AWS::RDS::DBInstance  
    DeletionPolicy: Retain
    Properties:
      AllowMajorVersionUpgrade: false
      BackupRetentionPeriod: 1
      DBInstanceClass: db.r4.large
      DBInstanceIdentifier: !Sub ${ServiceName}-${ClusterName}-${AWS::Region}
      DBName: !Ref DBName
      DBSubnetGroupName:
        Fn::ImportValue:
          !Sub harbour:${AWS::Region}:${ClusterName}:RDSSubnetGroup
      Engine: aurora
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      PubliclyAccessible: false
      StorageEncrypted: true
      Tags:
        - Key: Name
          Value: !Sub pies ${ClusterName}
        - Key: Role
          Value: Dev
        - Key: Service
          Value: Pies
        - Key: Business-Unit
          Value: INFRE
        - Key: Owner
          Value: INFENG
      VPCSecurityGroups:
        - Fn::ImportValue:
            !Sub harbour:${AWS::Region}:${ClusterName}:RDSSecurityGroup
