---
AWSTemplateFormatVersion: '2010-09-09'
Description: Another Stack For Science
Parameters:
  BucketName:
    Description: Name of Bucket
    Type: String
Resources:
  CFDeployerS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
        - Id: ClearOldFiles
          ExpirationInDays: 30
          Status: Enabled
