---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketName:
    Description: Name of Bucket
    Type: String
Resources:
  CFDeployerS3Bucket:
    AccessControl: Private
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
        - Id: ClearOldFiles
          ExpirationInDays: 30
          Status: Enabled
