---
image:
  registry: drydock.workiva.net
  repo: ericlarssen-wf/pies
  tag: '1562688'
replicas: 2
minAvailable: 75%
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: cpu
      average_percent: 75
ingress:
  clusterDomain: 'inf-dev.workiva.org'
  rules:
    - subDomain: pies
      backends:
        - port: 5000
environment:
  MSG_URL: "tls://nats-nats.workiva.svc.cluster.local:4222"
  MSG_CA_CERT: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  FLASKIVA_AUTH_PROVIDER: 'github'
  GITHUB_CLIENT_ID: ''
  SERVER_NAME: ''
secrets:
  DATABASE_URI: ''
  SECRET_KEY: ''
  GITHUB_CLIENT_SECRET: ''
resources:
  limits:
    cpu: 1.00
    memory: 1024Mi
  requests:
    cpu: 1.00
    memory: 1024Mi
runAsRoot: false
readinessProbe:
  httpGet:
    httpHeaders:
      - name: Host
        value: pies.inf-dev.workiva.org
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 10
