{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "template.fullname" . }}
  labels:
    app: {{ template "template.name" . }}
    chart: {{ template "template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{- $message := "secrets.KEY is required" | replace "KEY" $key }}
  {{ $key }}: {{ required $message $value | toString | b64enc }}
  {{- end }}
{{- end }}
