apiVersion: v1
kind: Service
metadata:
  name: {{ template "template.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "template.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ template "template.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: webhook